### PR TITLE
Use `node-notifier`

### PR DESCRIPTION
**Pull request by Turbo87**
see #1 

This allows notifications on Windows and also on recent OS X versions without having to manually install `terminal-notifier`

### CODE REVIEW

**Comment by Turbo87** [comment]
notify

Screenshot from OS X Yosemite without `terminal-notifier` installed

**Comment by vsolovyov** [comment]
It sure is a bit nicer with a logo. But I definitely do not want for this very small and simple plugin that does it's job to integrate with a bloated package just for a logo.

https://github.com/mikaelbr/node-notifier even ships its own `terminal-notifier` and Windows `exe`s! I think that's totally unacceptable.

**Comment by Turbo87** [comment]
suit yourself, I'll fork it then...

**Comment by vsolovyov** [comment]
sure

**Comment by michaeljota** [comment]
@Turbo87 thank you. :).

**Pull request closed without merging**
